In [55]:
import pandas as pd

In [56]:
data = {
    'CustomerID': [101, 102, 103, 104, None, 106, 107],
    'CustomerName': ['Alice', 'BOB', 'Charlie', 'DAVE', None, 'eve', 'eve'],
    'Age': [25, None, 35, 40, 28, 30, 30],
    'OrderDate': ['2023/01/15', '2023-02-20', 'March 10, 2023', None, '2023/04/10', '2023-05-05', 'InvalidDate'],
    'OrderAmount': [200, 300, None, 400, 250, None, 150],
    'Region': ['North', 'South', 'East', None, 'West', 'South', 'East'],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', None, 'Clothing'],
    'FeedbackScore': [5, 3, None, 4, 2, None, -1],
    'ExtraColumn': [None, None, None, None, None, None, None]
}

In [57]:
df = pd.DataFrame(data)
df

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,CustomerID,CustomerName,Age,OrderDate,OrderAmount,Region,Category,FeedbackScore,ExtraColumn
0,101.0,Alice,25.0,2023/01/15,200.0,North,Electronics,5.0,None
1,102.0,BOB,NaN,2023-02-20,300.0,South,Clothing,3.0,None
2,103.0,Charlie,35.0,"March 10, 2023",NaN,East,Electronics,NaN,None
3,104.0,DAVE,40.0,None,400.0,None,Furniture,4.0,None
4,NaN,None,28.0,2023/04/10,250.0,West,Clothing,2.0,None
5,106.0,eve,30.0,2023-05-05,NaN,South,None,NaN,None
6,107.0,eve,30.0,InvalidDate,150.0,East,Clothing,-1.0,None

In [67]:
df.drop(columns=['ExtraColumn'])

df['CustomerID'] = df['CustomerID'].fillna(method='ffill').astype(int)  
df['CustomerName'] = df['CustomerName'].fillna('Unknown').str.title() 
df['Age'] = df['Age'].fillna(round(df['Age'].mean(), 2))
df['OrderAmount'] = df['OrderAmount'].fillna(0) 
df['Region'] = df['Region'].fillna('Unknown')
df['Category'] = df['Category'].fillna('Miscellaneous') 
df['FeedbackScore'] = df['FeedbackScore'].fillna(0)

df

<ipython-input-67-a78c82151515>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['CustomerID'] = df['CustomerID'].fillna(method='ffill').astype(int)

,CustomerID,CustomerName,Age,OrderDate,OrderAmount,Region,Category,FeedbackScore,ExtraColumn,OrderYear,OrderMonth,AgeGroup
0,101,Alice,25.000000,2023-01-15,200.0,North,Electronics,5.0,None,2023,1,Young Adult
1,102,Bob,31.333333,2023-01-01,300.0,South,Clothing,3.0,None,2023,1,Young Adult
2,103,Charlie,35.000000,2023-01-01,0.0,East,Electronics,0.0,None,2023,1,Young Adult
3,104,Dave,40.000000,2023-01-01,400.0,Unknown,Furniture,4.0,None,2023,1,Adult
4,104,Unknown,28.000000,2023-04-10,250.0,West,Clothing,2.0,None,2023,4,Young Adult
5,106,Eve,30.000000,2023-01-01,0.0,South,Miscellaneous,0.0,None,2023,1,Young Adult

In [59]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce')

df['OrderDate'] = df['OrderDate'].fillna(pd.Timestamp('2023-01-01'))

print(df)

   CustomerID CustomerName        Age  OrderDate  OrderAmount   Region  \
0         101        Alice  25.000000 2023-01-15        200.0    North
1         102          Bob  31.333333 2023-01-01        300.0    South
2         103      Charlie  35.000000 2023-01-01          0.0     East
3         104         Dave  40.000000 2023-01-01        400.0  Unknown
4         104      Unknown  28.000000 2023-04-10        250.0     West
5         106          Eve  30.000000 2023-01-01          0.0    South
6         107          Eve  30.000000 2023-01-01        150.0     East

        Category  FeedbackScore ExtraColumn
0    Electronics            5.0        None
1       Clothing            3.0        None
2    Electronics            0.0        None
3      Furniture            4.0        None
4       Clothing            2.0        None
5  Miscellaneous            0.0        None
6       Clothing           -1.0        None

In [60]:
df = df.drop_duplicates(subset=['CustomerID', 'OrderDate'])

df = df[df['FeedbackScore'] >= 0]

In [61]:
df['OrderYear'] = df['OrderDate'].dt.year  
df['OrderMonth'] = df['OrderDate'].dt.month

In [62]:
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 18, 35, 50, 100], labels=['Teen', 'Young Adult', 'Adult', 'Senior'])

In [63]:
df

,CustomerID,CustomerName,Age,OrderDate,OrderAmount,Region,Category,FeedbackScore,ExtraColumn,OrderYear,OrderMonth,AgeGroup
0,101,Alice,25.000000,2023-01-15,200.0,North,Electronics,5.0,None,2023,1,Young Adult
1,102,Bob,31.333333,2023-01-01,300.0,South,Clothing,3.0,None,2023,1,Young Adult
2,103,Charlie,35.000000,2023-01-01,0.0,East,Electronics,0.0,None,2023,1,Young Adult
3,104,Dave,40.000000,2023-01-01,400.0,Unknown,Furniture,4.0,None,2023,1,Adult
4,104,Unknown,28.000000,2023-04-10,250.0,West,Clothing,2.0,None,2023,4,Young Adult
5,106,Eve,30.000000,2023-01-01,0.0,South,Miscellaneous,0.0,None,2023,1,Young Adult